import java.text.DateFormat
import java.text.SimpleDateFormat

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.kapt'
}

def currentTime = getCurrentTime()

static def getCurrentTime() {
    DateFormat df = new SimpleDateFormat("yyyy-MM-dd")
    return df.format(Calendar.getInstance(Locale.CHINA).getTime())
}

android {
    namespace 'com.bg7yoz.ft8cn'
    compileSdk 33

    defaultConfig {
        applicationId "com.bg7yoz.ft8cn.ft4"
        minSdk 28
        targetSdk 33
        versionCode 1
        versionName 'ver0.7-WSJT-Lib-b4'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

        buildFeatures {
            dataBinding true
            compose true
        }

        ndk {
            abiFilters 'arm64-v8a'
        }

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared"
                cppFlags ""
            }
        }

        signingConfig signingConfigs.debug
    }

    buildTypes {
        debug {
            buildConfigField "String", "apkBuildTime", "\"${currentTime}\""
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField "String", "apkBuildTime", "\"${currentTime}\""
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += ['-Xjvm-default=all']
    }

    composeOptions {
        kotlinCompilerExtensionVersion '1.4.3'
    }

    testOptions {
        unitTests.includeAndroidResources = true
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
            java.srcDir "$rootDir/third_party/sgp4/src/main/java"
        }
        test.assets.srcDirs += files("$projectDir/schemas")
        androidTest.assets.srcDirs += files("$projectDir/schemas")
    }

    packagingOptions {
        resources.excludes += [
                'META-INF/AL2.0',
                'META-INF/LGPL2.1'
        ]
    }
}

kapt {
    arguments {
        arg('room.schemaLocation', "$projectDir/schemas")
        arg('room.incremental', 'true')
        arg('room.expandProjection', 'true')
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.lifecycle:lifecycle-livedata:2.5.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.5.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.navigation:navigation-fragment:2.5.3'
    implementation 'androidx.navigation:navigation-ui:2.5.3'
    implementation 'com.google.android.gms:play-services-maps:18.1.0'
    implementation 'com.google.guava:guava:31.1-jre'

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4'
    implementation 'androidx.activity:activity-compose:1.7.0'
    implementation 'androidx.compose.ui:ui:1.4.0'
    implementation 'androidx.compose.ui:ui-tooling-preview:1.4.0'
    implementation 'androidx.compose.material3:material3:1.0.1'
    implementation 'androidx.navigation:navigation-compose:2.5.3'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-compose:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.6.1'
    implementation 'androidx.room:room-runtime:2.5.2'
    implementation 'androidx.room:room-ktx:2.5.2'
    kapt 'androidx.room:room-compiler:2.5.2'
    implementation 'androidx.datastore:datastore-preferences:1.0.0'
    implementation 'androidx.work:work-runtime-ktx:2.8.1'

    implementation files('src/libs/MPAndroidChartv_3.1.0.jar')
    implementation files('src/libs/commons-net-3.6.jar')
    implementation files('src/libs/nanohttpd-2.2.0.jar')
    implementation files('src/libs/osmdroid-android-6.1.14.aar')

    debugImplementation 'androidx.compose.ui:ui-tooling:1.4.0'
    debugImplementation 'androidx.compose.ui:ui-test-manifest:1.4.0'
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.12'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.4'
    testImplementation 'androidx.test:core:1.5.0'
    testImplementation 'androidx.test:runner:1.5.2'
    testImplementation 'androidx.room:room-testing:2.5.2'
    testImplementation 'org.robolectric:robolectric:4.10.3'

    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.room:room-testing:2.5.2'
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4:1.4.0'
}
